<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => '智能WIFI是什么？',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0428/20140428100405804.jpg',
    'keywords' => '智能 WIFI 移动',
    'description' => '世界在发展，移动改变生活',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1398685273',
    'updatetime' => '1409897027',
    'hitsid' => 'c-1-1',
    'views' => '83',
    'yesterdayviews' => '1',
    'dayviews' => '3',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => '引领上网卡革命无线网络村村通',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/poster/3g.png',
    'keywords' => '引领上网卡革命',
    'description' => '引领上网卡革命无线网络村村通',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1398698890',
    'updatetime' => '1410248737',
    'hitsid' => 'c-1-2',
    'views' => '58',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '9',
  ),
  18 => 
  array (
    'id' => '18',
    'catid' => '6',
    'typeid' => '0',
    'title' => '微志愿与单病种随访',
    'style' => '#9900FF',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0829/20140829034641720.png',
    'keywords' => '病种随访',
    'description' => '微锤子借用微信平台，研发出微志愿管理平台；单病种随访系统，已经试运行，赞一个！',
    'posids' => '1',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=18',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1409294379',
    'updatetime' => '1410306879',
    'hitsid' => 'c-1-18',
    'views' => '55',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '3',
    'monthviews' => '37',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '6',
    'typeid' => '0',
    'title' => '嘀嘀和快的：打车软件的今生与来世',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0518/20140518084231852.jpg',
    'keywords' => '打车软件',
    'description' => '打车软件可能成为一个广泛的产品和劳务的定价、交易平台，改变众多业态。打车软件会改变治霾治堵思路。打车软件因为出租车而起，最终又很可能彻底改变出租车业的业态。',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1400416927',
    'updatetime' => '1409890946',
    'hitsid' => 'c-1-10',
    'views' => '48',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '6',
    'typeid' => '0',
    'title' => '[创新业务]：动态表单技术',
    'style' => '',
    'thumb' => '',
    'keywords' => '动态 表单',
    'description' => '如何快速的应对客户的需求，提供更好的业务响应能力，使用动态的元数据技术解决B S应用的动态表单技术。',
    'posids' => '1',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405836207',
    'updatetime' => '1410248068',
    'hitsid' => 'c-1-15',
    'views' => '41',
    'yesterdayviews' => '7',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '37',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '6',
    'typeid' => '0',
    'title' => 'XP系统退役 工信部呼吁支持发展国产操作系统',
    'style' => '',
    'thumb' => '',
    'keywords' => '国产 系统',
    'description' => '谁将成为Windows XP的替代者？',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'Phpcms',
    'inputtime' => '1400311529',
    'updatetime' => '1409618410',
    'hitsid' => 'c-1-7',
    'views' => '33',
    'yesterdayviews' => '12',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '6',
    'typeid' => '0',
    'title' => '大企业ERP,如果小企业想要用怎么办？',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0827/20140827014508536.jpg',
    'keywords' => '小企业 怎么办 企业 ERP',
    'description' => 'ERP系统是指建立在信息技术基础上，以系统化的管理思想，为企业决策层及员工提供决策运行手段的管理平台。',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1409118163',
    'updatetime' => '1410248093',
    'hitsid' => 'c-1-17',
    'views' => '31',
    'yesterdayviews' => '5',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '19',
  ),
  19 => 
  array (
    'id' => '19',
    'catid' => '6',
    'typeid' => '0',
    'title' => '百万腾融合，O2O的春天来了！',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0830/20140830063836448.jpg',
    'keywords' => '百万腾融合，O2O的春天来了！',
    'description' => ' : 万达做电商有着强大的线下资源，又有着强大决心做线上线下消费融合，以前缺乏的只是互联网的思维和技术改造，而如今三大巨头的联合，定会如王健林所说，“一说淘宝，大家都知道就是',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=19',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1409395068',
    'updatetime' => '1410175913',
    'hitsid' => 'c-1-19',
    'views' => '26',
    'yesterdayviews' => '4',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '10',
  ),
  85 => 
  array (
    'id' => '85',
    'catid' => '6',
    'typeid' => '0',
    'title' => '考试招生制度改革启动 上海浙江试点不分文理',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0904/20140904123159719.jpg',
    'keywords' => '文理 考试招生 浙江',
    'description' => '[摘要]高考改革方案公布：高中不再分文理科，原文理6科选3门成绩计入总分，外语可考2次，上海浙江今年率先试点。明年起扩大使用全国卷省份，取消特长生加分。
',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=85',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1409804761',
    'updatetime' => '1409876907',
    'hitsid' => 'c-1-85',
    'views' => '23',
    'yesterdayviews' => '19',
    'dayviews' => '4',
    'weekviews' => '23',
    'monthviews' => '23',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '6',
    'typeid' => '0',
    'title' => '全球十大年轻亿万富翁出炉 中国仅一位上榜',
    'style' => '',
    'thumb' => '',
    'keywords' => '中国 富翁 全球',
    'description' => '近期，外国知名个人金融服务网站Bankrate评选了全球十位最年轻的亿万富翁，而其中一半来自美国,中国仅一位上榜。排名如下（单位：美元）：   ',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1400347821',
    'updatetime' => '1410033862',
    'hitsid' => 'c-1-9',
    'views' => '19',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
);
?>