<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => '智能WIFI是什么？',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0428/20140428100405804.jpg',
    'keywords' => '智能 WIFI 移动',
    'description' => '世界在发展，移动改变生活',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1398685273',
    'updatetime' => '1400637035',
    'hitsid' => 'c-1-1',
    'views' => '68',
    'yesterdayviews' => '32',
    'dayviews' => '3',
    'weekviews' => '4',
    'monthviews' => '52',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => '引领上网卡革命无线网络村村通',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/poster/3g.png',
    'keywords' => '引领上网卡革命',
    'description' => '引领上网卡革命无线网络村村通',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1398698890',
    'updatetime' => '1400637142',
    'hitsid' => 'c-1-2',
    'views' => '38',
    'yesterdayviews' => '5',
    'dayviews' => '2',
    'weekviews' => '3',
    'monthviews' => '31',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '6',
    'typeid' => '0',
    'title' => 'XP系统退役 工信部呼吁支持发展国产操作系统',
    'style' => '',
    'thumb' => '',
    'keywords' => '国产 系统',
    'description' => '谁将成为Windows XP的替代者？',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'Phpcms',
    'inputtime' => '1400311529',
    'updatetime' => '1400634921',
    'hitsid' => 'c-1-7',
    'views' => '27',
    'yesterdayviews' => '12',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '27',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '6',
    'typeid' => '0',
    'title' => '嘀嘀和快的：打车软件的今生与来世',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0518/20140518084231852.jpg',
    'keywords' => '打车软件',
    'description' => '打车软件可能成为一个广泛的产品和劳务的定价、交易平台，改变众多业态。打车软件会改变治霾治堵思路。打车软件因为出租车而起，最终又很可能彻底改变出租车业的业态。',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1400416927',
    'updatetime' => '1400607439',
    'hitsid' => 'c-1-10',
    'views' => '19',
    'yesterdayviews' => '2',
    'dayviews' => '2',
    'weekviews' => '11',
    'monthviews' => '19',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '6',
    'typeid' => '0',
    'title' => '测试3G',
    'style' => '',
    'thumb' => '',
    'keywords' => '测试3G',
    'description' => '测试3G',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1398700093',
    'updatetime' => '1400391964',
    'hitsid' => 'c-1-3',
    'views' => '12',
    'yesterdayviews' => '4',
    'dayviews' => '2',
    'weekviews' => '11',
    'monthviews' => '11',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '6',
    'typeid' => '0',
    'title' => '全球十大年轻亿万富翁出炉 中国仅一位上榜',
    'style' => '',
    'thumb' => '',
    'keywords' => '中国 富翁 全球',
    'description' => '近期，外国知名个人金融服务网站Bankrate评选了全球十位最年轻的亿万富翁，而其中一半来自美国,中国仅一位上榜。排名如下（单位：美元）：   ',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1400347821',
    'updatetime' => '1400634244',
    'hitsid' => 'c-1-9',
    'views' => '11',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '11',
  ),
);
?>