<?php
return array (
  15 => 
  array (
    'id' => '15',
    'catid' => '6',
    'typeid' => '0',
    'title' => '[创新业务]：动态表单技术',
    'style' => '',
    'thumb' => '',
    'keywords' => '动态 表单',
    'description' => '如何快速的应对客户的需求，提供更好的业务响应能力，使用动态的元数据技术解决B S应用的动态表单技术。',
    'posids' => '1',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405836207',
    'updatetime' => '1410248068',
    'hitsid' => 'c-1-15',
    'views' => '41',
    'yesterdayviews' => '7',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '37',
  ),
  18 => 
  array (
    'id' => '18',
    'catid' => '6',
    'typeid' => '0',
    'title' => '微志愿与单病种随访',
    'style' => '#9900FF',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0829/20140829034641720.png',
    'keywords' => '病种随访',
    'description' => '微锤子借用微信平台，研发出微志愿管理平台；单病种随访系统，已经试运行，赞一个！',
    'posids' => '1',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=18',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1409294379',
    'updatetime' => '1410306879',
    'hitsid' => 'c-1-18',
    'views' => '55',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '3',
    'monthviews' => '37',
  ),
  85 => 
  array (
    'id' => '85',
    'catid' => '6',
    'typeid' => '0',
    'title' => '考试招生制度改革启动 上海浙江试点不分文理',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0904/20140904123159719.jpg',
    'keywords' => '文理 考试招生 浙江',
    'description' => '[摘要]高考改革方案公布：高中不再分文理科，原文理6科选3门成绩计入总分，外语可考2次，上海浙江今年率先试点。明年起扩大使用全国卷省份，取消特长生加分。
',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=85',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1409804761',
    'updatetime' => '1409876907',
    'hitsid' => 'c-1-85',
    'views' => '23',
    'yesterdayviews' => '19',
    'dayviews' => '4',
    'weekviews' => '23',
    'monthviews' => '23',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '6',
    'typeid' => '0',
    'title' => '大企业ERP,如果小企业想要用怎么办？',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0827/20140827014508536.jpg',
    'keywords' => '小企业 怎么办 企业 ERP',
    'description' => 'ERP系统是指建立在信息技术基础上，以系统化的管理思想，为企业决策层及员工提供决策运行手段的管理平台。',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1409118163',
    'updatetime' => '1410248093',
    'hitsid' => 'c-1-17',
    'views' => '31',
    'yesterdayviews' => '5',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '19',
  ),
  67 => 
  array (
    'id' => '67',
    'catid' => '6',
    'typeid' => '0',
    'title' => '湖南岳阳医生遭殴打 急诊科主任倡议拒诊打人者|湖南医患',
    'style' => '',
    'thumb' => 'http://i2.sinaimg.cn/dy/c/2014-09-01/U7939P1T1D30776915F21DT20140901150809.jpg',
    'keywords' => '',
    'description' => '    微博截图。易峰的倡议短信　　相距不过10天，湖南岳阳再现医患纠纷。　　因有医护人员遭恐吓、殴打，岳阳市一医院急诊科主任发出倡   ',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=67',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1409563240',
    'updatetime' => '1410248711',
    'hitsid' => 'c-1-67',
    'views' => '18',
    'yesterdayviews' => '4',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '18',
  ),
  111 => 
  array (
    'id' => '111',
    'catid' => '6',
    'typeid' => '0',
    'title' => '新手上路，听听老司机的忠告',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0909/20140909080559587.jpg',
    'keywords' => '',
    'description' => '新手上路，听听老司机的忠告图片：Isaac Mao   CC BY资深驾驶员对新手有哪些建议？安迪，Developper 互联网关注者 汽车爱好者父亲驾龄   ',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=111',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1410220739',
    'updatetime' => '1410248077',
    'hitsid' => 'c-1-111',
    'views' => '12',
    'yesterdayviews' => '0',
    'dayviews' => '12',
    'weekviews' => '12',
    'monthviews' => '12',
  ),
  19 => 
  array (
    'id' => '19',
    'catid' => '6',
    'typeid' => '0',
    'title' => '百万腾融合，O2O的春天来了！',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0830/20140830063836448.jpg',
    'keywords' => '百万腾融合，O2O的春天来了！',
    'description' => ' : 万达做电商有着强大的线下资源，又有着强大决心做线上线下消费融合，以前缺乏的只是互联网的思维和技术改造，而如今三大巨头的联合，定会如王健林所说，“一说淘宝，大家都知道就是',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=19',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1409395068',
    'updatetime' => '1410175913',
    'hitsid' => 'c-1-19',
    'views' => '26',
    'yesterdayviews' => '4',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '10',
  ),
  96 => 
  array (
    'id' => '96',
    'catid' => '6',
    'typeid' => '0',
    'title' => '非医学需要鉴定胎儿性别最高或可追刑责|鉴定婴儿性别|刑',
    'style' => '',
    'thumb' => 'http://i3.sinaimg.cn/dy/c/2014-09-05/U10471P1T1D30797401F21DT20140905034209.jpg',
    'keywords' => '',
    'description' => '    鉴定婴儿性别　　据新华社电9月3日，国家卫生计生委、公安部、工商总局、食品药品监管总局等共同起草的新规《禁止非医学需要的胎儿   ',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=96',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1409877417',
    'updatetime' => '1410248715',
    'hitsid' => 'c-1-96',
    'views' => '10',
    'yesterdayviews' => '8',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '10',
  ),
);
?>