<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '17',
    'typeid' => '0',
    'title' => '星映话-《归来：洗尽铅华》',
    'style' => '',
    'thumb' => '',
    'keywords' => '星映话-《归来：洗尽铅华》',
    'description' => '星映话-《归来：洗尽铅华》',
    'posids' => '1',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=17&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1400418967',
    'updatetime' => '1400681143',
    'hitsid' => 'c-14-4',
    'views' => '18',
    'yesterdayviews' => '1',
    'dayviews' => '4',
    'weekviews' => '12',
    'monthviews' => '18',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '17',
    'typeid' => '0',
    'title' => '舌尖上的中国 第二季：相逢',
    'style' => '',
    'thumb' => '',
    'keywords' => '舌尖上 相逢',
    'description' => '舌尖上 相逢',
    'posids' => '1',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=17&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1400383924',
    'updatetime' => '1400636948',
    'hitsid' => 'c-14-3',
    'views' => '10',
    'yesterdayviews' => '1',
    'dayviews' => '2',
    'weekviews' => '3',
    'monthviews' => '10',
  ),
);
?>