<?php
return array (
  6 => 
  array (
    'id' => '6',
    'catid' => '11',
    'typeid' => '0',
    'title' => '帮助别人，快乐自己',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0712/20140712032910166.jpg',
    'keywords' => '桐城软件，网站建设',
    'description' => '桐城区青腾小软件工作室   ',
    'posids' => '1',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=11&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'Phpcms',
    'inputtime' => '1400303885',
    'updatetime' => '1410248053',
    'hitsid' => 'c-1-6',
    'views' => '242',
    'yesterdayviews' => '2',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '20',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '11',
    'typeid' => '0',
    'title' => '扬帆起航',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0519/20140519041832599.jpg',
    'keywords' => '扬帆起航，2014',
    'description' => 'http:  www cyznj com  微锤子 我们开始扬帆起航，加油伟大的2014，伟大的锤子，颠覆就在新的互联网时代！',
    'posids' => '1',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=11&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1400480210',
    'updatetime' => '1410248113',
    'hitsid' => 'c-1-12',
    'views' => '126',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '18',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '11',
    'typeid' => '0',
    'title' => '企业微信管理平台方案',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0530/20140530025005559.jpg',
    'keywords' => '企业',
    'description' => '随心所欲的设计理念, 北京展会客户体验',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=11&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1401432214',
    'updatetime' => '1410239996',
    'hitsid' => 'c-1-13',
    'views' => '61',
    'yesterdayviews' => '7',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '12',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '11',
    'typeid' => '0',
    'title' => '精英加盟',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0530/20140530040011742.jpg',
    'keywords' => '精英',
    'description' => '拿起手中的锤子，做回真正的你',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=11&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1401436528',
    'updatetime' => '1410240026',
    'hitsid' => 'c-1-14',
    'views' => '49',
    'yesterdayviews' => '8',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '22',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '11',
    'typeid' => '0',
    'title' => '家乡桐城的老板，请您联系我！',
    'style' => '',
    'thumb' => '',
    'keywords' => '桐城 家乡 老板 软件管理',
    'description' => '我希望在桐城有很多企业的老板找我做软件，我知道在我们这个小城大家可能都不知道软件是什么，所以我选择在这里创业，因为这里大家什么都不   ',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=11&id=16',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1408807205',
    'updatetime' => '1410239778',
    'hitsid' => 'c-1-16',
    'views' => '37',
    'yesterdayviews' => '6',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '20',
  ),
  70 => 
  array (
    'id' => '70',
    'catid' => '11',
    'typeid' => '0',
    'title' => '大企业ERP,如果小企业想要用怎么办？',
    'style' => '',
    'thumb' => 'http://www.cyznj.com/uploadfile/2014/0827/20140827014508536.jpg',
    'keywords' => '小企业 怎么办 企业 ERP',
    'description' => 'ERP系统是指建立在信息技术基础上，以系统化的管理思想，为企业决策层及员工提供决策运行手段的管理平台。',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1409118163',
    'updatetime' => '1409628174',
    'hitsid' => 'c-1-70',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  71 => 
  array (
    'id' => '71',
    'catid' => '11',
    'typeid' => '0',
    'title' => '[创新业务]：动态表单技术',
    'style' => '',
    'thumb' => '',
    'keywords' => '动态 表单',
    'description' => '如何快速的应对客户的需求，提供更好的业务响应能力，使用动态的元数据技术解决B S应用的动态表单技术。',
    'posids' => '0',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1405836207',
    'updatetime' => '1409628174',
    'hitsid' => 'c-1-71',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>