<?php
return array (
  0 => 
  array (
    'commentid' => 'content_17-4-1',
    'siteid' => '1',
    'title' => '星映话-《归来：洗尽铅华》',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=17&id=4',
    'total' => '5',
    'square' => '3',
    'anti' => '0',
    'neutral' => '0',
    'display_type' => '1',
    'tableid' => '1',
    'lastupdate' => '1400419317',
  ),
  1 => 
  array (
    'commentid' => 'content_11-12-1',
    'siteid' => '1',
    'title' => '杨帆起航',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=11&id=12',
    'total' => '5',
    'square' => '1',
    'anti' => '0',
    'neutral' => '0',
    'display_type' => '1',
    'tableid' => '1',
    'lastupdate' => '1400516192',
  ),
  2 => 
  array (
    'commentid' => 'content_6-1-1',
    'siteid' => '1',
    'title' => '创业的过程',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=1',
    'total' => '3',
    'square' => '1',
    'anti' => '0',
    'neutral' => '0',
    'display_type' => '0',
    'tableid' => '1',
    'lastupdate' => '1400416359',
  ),
  3 => 
  array (
    'commentid' => 'content_6-10-1',
    'siteid' => '1',
    'title' => '嘀嘀和快的：打车软件的今生与来世',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=10',
    'total' => '2',
    'square' => '1',
    'anti' => '1',
    'neutral' => '0',
    'display_type' => '1',
    'tableid' => '1',
    'lastupdate' => '1400490628',
  ),
  4 => 
  array (
    'commentid' => 'content_6-7-1',
    'siteid' => '1',
    'title' => 'XP系统退役 工信部呼吁支持发展国产操作系统',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=7',
    'total' => '1',
    'square' => '0',
    'anti' => '0',
    'neutral' => '0',
    'display_type' => '0',
    'tableid' => '1',
    'lastupdate' => '1400341409',
  ),
  5 => 
  array (
    'commentid' => 'content_12-8-1',
    'siteid' => '1',
    'title' => '舌尖上的中国 第二季：相逢',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=12&id=8',
    'total' => '1',
    'square' => '1',
    'anti' => '0',
    'neutral' => '0',
    'display_type' => '1',
    'tableid' => '1',
    'lastupdate' => '1400348775',
  ),
  6 => 
  array (
    'commentid' => 'content_6-2-1',
    'siteid' => '1',
    'title' => '引领上网卡革命无线网络村村通',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=6&id=2',
    'total' => '1',
    'square' => '0',
    'anti' => '0',
    'neutral' => '0',
    'display_type' => '0',
    'tableid' => '1',
    'lastupdate' => '1400348912',
  ),
  7 => 
  array (
    'commentid' => 'content_8-1-1',
    'siteid' => '1',
    'title' => '微云端 承接定制服务',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=8&id=1',
    'total' => '1',
    'square' => '1',
    'anti' => '0',
    'neutral' => '0',
    'display_type' => '1',
    'tableid' => '1',
    'lastupdate' => '1400407216',
  ),
  8 => 
  array (
    'commentid' => 'content_11-6-1',
    'siteid' => '1',
    'title' => '帮助别人，快乐自己',
    'url' => 'http://www.cyznj.com/index.php?m=content&c=index&a=show&catid=11&id=6',
    'total' => '1',
    'square' => '0',
    'anti' => '0',
    'neutral' => '0',
    'display_type' => '0',
    'tableid' => '1',
    'lastupdate' => '1400657651',
  ),
);
?>